### ISSUE TITLE
PR #47 needs to go to prod before noon on Feb 13th

### ISSUE THREAD

**Issue by jtesta** [chorn/bsidesroc#48]
PR #47 updates the instructions for the resume program, and the big ticket announcement goes out at noon on Feb 13th.  Pushing this to prod by then would be a good idea.

**Comment by antitree** [comment]
what are you doing?

**Comment by jtesta** [comment]
I was asking for the instructions to be pushed to prod.  For over a week, the website gave out the wrong steps, leading to a lot more manual work on my end to straighten things out.

It appears to be fixed now.
